# Generated by Django 3.2 on 2021-05-06 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_auto_20210504_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='gamer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='levelupapi.gamer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='maker',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default='2021-06-20'),
            preserve_default=False,
        ),
    ]
